@startuml
'https://plantuml.com/sequence-diagram

autonumber
== sekcja 1: dodawanie aktywnosci ==
user -> Frontend: dodaj aktywność
Frontend -> Engine: user chce dodac aktywnosc
Engine -> DB: odbiera info o aktynosci i dodaje
Frontend <- Engine: another authentication Response
user <- Frontend: dodano aktywnosc
==  sekcja 2: wyswietlanie strony głownej ==
user -> Frontend : wyswietl strone glona
Frontend -> Engine : żądanie wyswietlenia strny glownej
Engine -> DB: żądanie ostatnich aktywnosci uzytownikow i celow zalogowanego
DB -> Engine : wyslanie danych ostatnich aktywnosci
Engine -> Frontend: wyslanie danych ostatnich aktywnosci
Frontend -> user : wyswietlnie danych ostatnich aktywnosci
== sekcja 3: sprawdzanie progresu ==
user -> Frontend : pokaz moje podsumowanie - progres
Frontend -> Engine : żądanie wyswietlenia progresu
Engine -> DB: żądanie progresu
DB -> Engine : wyslanie danych ostatnich aktywnosci podsumowanych
Engine -> Frontend: wyslanie danych ostatnich aktywnosci podsumowanych
Frontend -> user : wyswietlnie danych w tabelce (podsumowanie progresu)
== sekcja 4: logowanie ==
user -> Frontend : podaje dane i zaloguj sie
Frontend -> Engine : żądanie zalogowania z danymi
Engine -> DB: żądanie zalogowania danymi
DB --> Engine : wyslanie danych powiazanych z nickiem
Engine --> Frontend: sprawdzenie prawidlowe - zalogowano
Frontend --> user : zalogowano
Engine --> Frontend : bledne dane - sprobuj ponownie
Frontend --> user : nieudane logowanie, wpisz prawidlowe dane
== sekcja 5: rejestracja ==
user -> Frontend : podaje dane i zarejestruj sie
Frontend -> Engine : żądanie rejestracji z danymi
Engine -> DB: żądanie rejestracji danymi
DB --> Engine : wyslanie danych powiazanych z nickiem
Engine --> Frontend: sprawdzenie prawidlowe - stworzono nowe konto
Frontend --> user : zalogowano
Engine --> Frontend : bledne dane - sprobuj ponownie
Frontend --> user : nieudana rejestracja, wpisz prawidlowe dane
== sekcja 6: edycja aktywności ==
user -> Frontend : podanie danych do edycji aktywnosci
Frontend -> Engine : żądanie edycji aktywnosci
Engine -> DB: żądanie edycji aktywnosci
DB --> Engine : wyslanie danych powiazanych z aktywnoscia
Engine --> Frontend: sprawdzenie prawidlowe - edytowano aktywnosc
Frontend --> user : edytowano aktywnosc
Engine --> Frontend : bledne dane - sprobuj ponownie
Frontend --> user : nieudana edycja, wpisz prawidlowe dane
== sekcja 7: edycja celów ==
user -> Frontend : podanie danych do edycji celów
Frontend -> Engine : żądanie edycji celów
Engine -> DB: żądanie edycji celów
DB -> Engine : wyslanie danych powiazanych z celami
Engine -> Frontend: sprawdzenie prawidlowe - edytowano cele
Frontend -> user : edytowano cele
== sekcja 8: polubienie aktywności ==
user -> Frontend : polubienie aktywnosci
Frontend -> Engine : informacja, że user chce polubić aktywność
Engine -> DB: żądanie polubienia aktywnosci
DB -> Engine : wyslanie danych powiazanych z aktywnością
Engine -> Frontend: aktualizacja aktywności
Frontend -> user : polubiono aktywność
@enduml
@startuml
== usuwanie aktywnosci ==
admin -> Frontend : usun aktywnosc danego uzytkowanika
Frontend -> Engine : żądanie usuniecia aktywnosci
Engine -> DB: żądanie usuniecia aktywnsoci
DB -> Engine : usunieto aktywnosc
Engine -> Frontend: usunieto aktywnosc
Frontend -> admin : usunieto aktywnosc
== permanentne banowanie uzytkownika ==
admin -> Frontend : zbanowanie uzytkownika
Frontend -> Engine : żądanie usuniecia danego uzytkowanika i aktywnosci
Engine -> DB: żądanie usuniecia uzytkownika i jego aktywnsoci
DB -> Engine : usunieto aktywnosci
DB -> Engine : usunieto uzytkownika
Engine -> Frontend: usunieto urztkownika i jego aktywnosci
Frontend -> admin : zbanowano uzytkownika
@enduml